name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: armbian/build
          path: build
      - name: Build Armbian
        run: |
          cd build
          cp -r ../userpatches .
          # 这是 Armbian 官方最标准的构建命令，没有多余的参数，不会触发嵌套报错
          sudo ./compile.sh BOARD=vontar-h618 BRANCH=current RELEASE=trixie BUILD_DESKTOP=no BUILD_MINIMAL=yes KERNEL_CONFIGURE=no
      - uses: actions/upload-artifact@v4
        with:
          name: image
          path: build/output/images/*.img.xz
