name: Build Armbian Image
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project patches
        uses: actions/checkout@v4
        with:
          path: vontar-h618-armbian-patche

      - name: Checkout Armbian build
        uses: actions/checkout@v4
        with:
          repository: armbian/build
          path: armbian-build

      - name: Add Swap Space
        run: |
          sudo fallocate -l 10G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Prepare build tree
        run: |
          cd armbian-build
          rm -rf userpatches
          ln -s ../vontar-h618-armbian-patche/userpatches userpatches

      - name: Build Armbian image
        run: |
          cd armbian-build
          sudo ./compile.sh BOARD=vontar-h618 BRANCH=current RELEASE=trixie \
            BUILD_DESKTOP=no BUILD_MINIMAL=yes KERNEL_CONFIGURE=no \
            FORCE_DOCKER=yes

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: armbian-vontar-h618
          path: armbian-build/output/images/*.img.xz
